### ISSUE TITLE
why 'the number of mask proposals is (100+Gt) during training'?

### ISSUE THREAD

**Issue by Davis-love-AI** [chengyangfu/retinamask#15]
Hi, I am very glad you share the retinamask, and I have some questions:
1. in your paper, you said training the mask subnet by (100+ GT),  why not GT? and I want have a try, so I need confirm if the (100+GT) is set in the fellow line:
( ../maskrcnn_benchmark/modeling/detector/retinanet.py )
                    """
                    proposals = []
                    for (image_detections, image_targets) in zip(detections, targets):
                        merge_list = []

                        if not isinstance(image_detections, list): 
                           merge_list.append(image_detections.copy_with_fields('labels'))
                        if not isinstance(image_targets, list):
                            merge_list.append(image_targets.copy_with_fields('labels'))

                        if len(merge_list) == 1: proposals.append(merge_list[0])
                        else: proposals.append(cat_boxlist(merge_list))
                    """
I mean, I want to just using gt for training, I want to delete the detection net's proposals. 
2. can you tell me ,if is it a practical way fo ignoring the mask net, and just training the detection, then freeze it, start train mask subnet? do you have any more experiment ?
Looking u reply.Thanks a lot.

**Comment by chengyangfu** [comment]
Hi @DeqiangWang, 
   I think using 100+GT can obtain a more robust instance segmentation. We hope the detection outs can be as same as the GT. However, there still exists a difference. Therefore,  adding these in the mask segmentation can make the instance segmentation part see different types of boxes in the training. I think that removing 100detection results in the training will cause the accuracy drop. P.S. Mask R-CNN also adopts a similar approach(100+GT). 
   In our case, you just need to remove the following lines. 
```
if not isinstance(image_detections, list):
   merge_list.append(image_detections.copy_with_fields('labels'))
```
  For the second part,  I personally prefer to train the entire network together. There are some works in Mask R-CNN showing multi-tasking training will give better accuracy for both tasks. I do not have the experiment of this in the repository. For the engineering issue/implementation, it is much simpler to train the network together than separately.

**Comment by Davis-love-AI** [comment]
ok, thx a lot, if I have some results I will tell you.
