### ISSUE TITLE
Will it work well on detection task of medical image?

### ISSUE THREAD

**Issue by Chen-Jingyi** [chengyangfu/retinamask#22]
## ❓ Questions and Help
Do you think it will work well on medical image?And do I have to run this code on 4 GPUs? 
Could you give me some advice?

**Comment by chengyangfu** [comment]
I think it should work, but I cannot guarantee the performance. If having less GPUs,  you could follow the linear policy by increasing the iterations and reducing the learning rate. 

For example, if you have 2 GPUs, 
Increase current Iteration 2time, decrease the BASE_LR to half. 

  BASE_LR: 0.01 -> 0.005
  STEPS: (60000, 80000) -> (120000, 160000)
  MAX_ITER: 90000 -> 180000
  IMS_PER_BATCH: 16 -> 8

**Comment by chengyangfu** [comment]
I think it should work, but I cannot guarantee the performance. If having less GPUs,  you could follow the linear policy by increasing the iterations and reducing the learning rate. 

For example, if you have 2 GPUs, 
Increase current Iteration 2time, decrease the BASE_LR to half. 

  BASE_LR: 0.01 -> 0.005
  STEPS: (60000, 80000) -> (120000, 160000)
  MAX_ITER: 90000 -> 180000
  IMS_PER_BATCH: 16 -> 8

**Comment by Chen-Jingyi** [comment]
Thanks for your quick and detailed reply,I got it .But I still have a superficial question:what level should the data annotations reach? Do I need to label data according to the data annotations for Instance segmentation work,or just for object detection work?
