### ISSUE TITLE
How can I see the image with "box"  and "mask" lables?

### ISSUE THREAD

**Issue by Chen-Jingyi** [chengyangfu/retinamask#24]
## ❓ Questions and Help
Sorry to bother you again.In fact,I didn't run it successfully because of my poor device.But I don't want to stop learning it ,I read the code,and found that the result of this project is some files ended with".pth", isn't it? If I want to see the image with "boxes" and "mask" label , should I write this part of the code?ThanKs again!

**Comment by Eldad27** [comment]
@Chen-Jingyi Did you manage to resolve this? Any update? I also noticed the Demo.ipynb file outputs an error message
