### ISSUE TITLE
how to merge retinamask to maskrcnn-benchmark?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [chengyangfu/retinamask#3]
what are the difference between retinamask and maskrcnn-benchmark (maybe the [pr102](https://github.com/facebookresearch/maskrcnn-benchmark/pull/102))? because i want merge retinamask into it. (for personal purpose).
thanks

**Comment by chengyangfu** [comment]
Hi @zimenglan-sysu-512 ,
The pr102 already merged all the new stuff in maskrcnn-benchmask master branch and I also changed some file naming and location in pr102 according to the discussion with maskrcnn-benchmark maintainers. 
 
However, retinamask is developed when the maskrcnn-benchmask just releasesd. So, many parts of code or naming needed to change to be changed according to the master branch of maskrcnn-benchmark.  

Currently, my plan is to help maskrcnn-benchmark to merge pr102 first then update retinamask.

**Comment by zimenglan-sysu-512** [comment]
thanks

**Comment by chengyangfu** [comment]
Hi @zimenglan-sysu-512 
     The results look good! 
     I evaluate the performance on COCO test-dev. But your result is very similar to my result on COCO-2017-Val.   

| Val set | BBox |  Mask  |
| --------  | ------ | --------- |
| COCO-2017-val | 39.0/57.8/41.8/21.9/42.7/52.8 | 34.5/54.8/36.9/14.8/37.3/51.9 |
| COCO-test-dev | 39.4/58.6/42.3/21.9/42.0/51.0 | 34.9/55.7/37.1/15.1/36.7/50.4 |

**Comment by zimenglan-sysu-512** [comment]
hi @chengyangfu 
yes, i test it on coco2017-val. it's very closed to your results.
thanks.
