### ISSUE TITLE
P6 is different from paper

### ISSUE THREAD

**Issue by hux999** [chengyangfu/retinamask#4]
It's mentioned in the original retinanet paper that P6 is generated by C5. But in this implementation, P6 is generated by P5. Did you have any experiment on these implementation?

**Comment by chengyangfu** [comment]
Hi @hux999 , 
    Someone also notified me this issue two weeks ago. I add the table testing P5 and C5. 
    You can check the information in my another thread. 
    https://github.com/facebookresearch/maskrcnn-benchmark/pull/102

    The performance difference is really minor. But using P5 is slightly memory efficient.
