### ISSUE TITLE
train on cityscapes

### ISSUE THREAD

**Issue by boundles** [chengyangfu/retinamask#6]
hi, have you trained on cityscapes? I trained on it and AP is very low.

**Comment by chengyangfu** [comment]
Hi, 
   Thanks for letting me know this. I haven't trained on Cityscapes dataset yet. As I know, training on Cityscapes needs some modification in config file especially the TRAIN AND TEST resolution. Besides, using the model trained on COCO as the pre-train model is also important.

**Comment by boundles** [comment]
> Hi,
> Thanks for letting me know this. I haven't trained on Cityscapes dataset yet. As I know, training on Cityscapes needs some modification in config file especially the TRAIN AND TEST resolution. Besides, using the model trained on COCO as the pre-train model is also important.

Do you have training log on coco shared with me? I trained it on coco and 'loss mask' drops very slow.

**Comment by chengyangfu** [comment]
Hi, 
    I am going to test it soon. But I have some works to do before the end of March. I may update the training related to Cityscapes after that.

**Comment by boundles** [comment]
> Hi,
> I am going to test it soon. But I have some works to do before the end of March. I may update the training related to Cityscapes after that.

ok, thanks a lot.
