### ISSUE TITLE
Issue about ImageNetPretrained weights

### ISSUE THREAD

**Issue by RenAihua** [chengyangfu/retinamask#8]
## ❓ Questions and Help
Hi, i can't get the ImageNetPretrained weights when run the train script. I just get the R-50.pkl just like : 
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>detectron</BucketName><RequestId>5FE2AB3EE4E35848</RequestId><HostId>51Vhi/Z1ck7Jayj7yY2muN495jIdfytq3QOLzmAaL0jneIhvQkirmRu6/0ZYIWr1XKCQtpgIFrM=</HostId></Error>
Error comes : _pickle.UnpicklingError: invalid load key, '<'.
How can i solve this issue or can you give me some other links.
@chengyangfu

**Comment by chengyangfu** [comment]
hi, 
I update the path of the ImageNet pretrained model and it should work now. Please let me know if this does not work.  

I modify from the maskrcnn-benchmark last November. It worked fine at that time. But FB changes the locations of their ImageNet Pretrained Model. I think that's the reason. Thanks for notifying me the error.

**Comment by Rguoo** [comment]
thanks a lot and it works very well now.

**Comment by chengyangfu** [comment]
Sounds good! Let me close this first.
